import { Destination } from "../types";

export const INDIAN_DESTINATIONS: Destination[] = [
  {
    id: "dest-gulmarg-kashmir",
    name: "Gulmarg & Kashmir Valley",
    state: "Jammu & Kashmir",
    region: "North India",
    tagline: "Paradise on Earth & Alpine Meadows",
    description:
      "Framed by the majestic Pir Panjal range, Gulmarg offers world-class skiing, the highest cable car (Gulmarg Gondola), serene pine valleys, and enchanting Shikara rides across Dal Lake in nearby Srinagar.",
    coverImage:
      "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1626014303757-6466542e7428?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 3420,
    costIndex: "₹₹₹",
    avgDailyCostINR: 6500,
    bestTimeToVisit: "October to April (Snow & Skiing) | May to September (Meadows & Lakes)",
    idealDuration: "4 - 6 Days",
    travelStyles: ["Mountains & Snow", "Romantic", "Adventure", "Culture"],
    topAttractions: [
      "Gulmarg Gondola (Phase 1 & 2 to Apharwat Peak)",
      "Dal Lake Shikara & Houseboat Stay (Srinagar)",
      "Strawberry Valley & Maharani Temple",
      "Pari Mahal & Mughal Gardens",
    ],
    signatureCuisine: ["Kashmiri Wazwan", "Rogan Josh", "Kahwa Tea with Saffron & Almonds", "Modur Pulao"],
    localTransitTips: [
      "Pre-book Gulmarg Gondola tickets online on JK Cable Car portal.",
      "Union Cabs operate from Tangmarg to Gulmarg with snow-chains in winter.",
    ],
    localLanguage: "Kashmiri, Urdu & Hindi",
    localPhrases: [
      { phrase: "Koshur chhu sahal?", meaning: "Is it easy?", pronunciation: "Koshur chhu sahal" },
      { phrase: "Shukriya / Mehrbani", meaning: "Thank you", pronunciation: "Shook-ree-ya" },
      { phrase: "War chhu?", meaning: "How are you?", pronunciation: "Wahr chhu" },
    ],
    isFeatured: true,
  },
  {
    id: "dest-jaipur-rajasthan",
    name: "Jaipur (The Pink City)",
    state: "Rajasthan",
    region: "West India",
    tagline: "Royal Forts, Palaces & Vibrant Bazaars",
    description:
      "The capital of Rajasthan is an architectural triumph with terracotta-pink facades, astronomical observatories, massive hilltop bastions, and royal thali dining.",
    coverImage:
      "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 5210,
    costIndex: "₹₹",
    avgDailyCostINR: 3800,
    bestTimeToVisit: "October to March (Pleasant winter sunshine)",
    idealDuration: "3 - 4 Days",
    travelStyles: ["Heritage & History", "Royal Architecture", "Culinary", "Shopping"],
    topAttractions: [
      "Hawa Mahal (Palace of Winds)",
      "Amer Fort & Sheesh Mahal",
      "City Palace & Museum",
      "Jantar Mantar UNESCO Observatory",
      "Nahargarh Fort Sunset Point",
    ],
    signatureCuisine: [
      "Dal Baati Churma with Ghee",
      "Laal Maas (Royal Mutton Curry)",
      "Pyaaz Kachori at Rawat Mishtan Bhandar",
      "Ghewar & Kulfi",
    ],
    localTransitTips: [
      "Jaipur Metro connects Railway Station to Chandpole & Old City.",
      "E-rickshaws are ideal for navigating Johari Bazaar and Bapu Bazaar.",
      "Vande Bharat Express links Delhi to Jaipur in under 4 hours.",
    ],
    localLanguage: "Rajasthani & Hindi",
    localPhrases: [
      { phrase: "Khamma Ghani", meaning: "Warm Greetings / Welcome", pronunciation: "Khum-ma Ghuh-nee" },
      { phrase: "Dhanyawad", meaning: "Thank you", pronunciation: "Dhun-yuh-waad" },
      { phrase: "Kai haal hai?", meaning: "How are you?", pronunciation: "Ka-ee haal hai" },
    ],
    isFeatured: true,
  },
  {
    id: "dest-munnar-kerala",
    name: "Munnar & Alleppey Backwaters",
    state: "Kerala",
    region: "South India",
    tagline: "Emerald Tea Terraces & Backwaters Houseboats",
    description:
      "A serene paradise where misty rolling tea hills give way to the palm-fringed lagoons of Alleppey. Cruise on a traditional Kettuvallam and experience authentic Ayurvedic rejuvenation.",
    coverImage:
      "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 4890,
    costIndex: "₹₹",
    avgDailyCostINR: 4200,
    bestTimeToVisit: "September to March | June to August (Monsoon rejuvenation)",
    idealDuration: "4 - 5 Days",
    travelStyles: ["Nature & Wildlife", "Wellness & Ayurveda", "Cruises", "Romantic"],
    topAttractions: [
      "Alleppey Backwaters Overnight Houseboat",
      "Kolukkumalai Tea Estate (World's highest tea plantation)",
      "Eravikulam National Park (Nilgiri Tahr)",
      "Mattupetty Dam & Kundala Lake",
      "Kathakali & Kalaripayattu Cultural Show",
    ],
    signatureCuisine: [
      "Kerala Sadhya on Banana Leaf",
      "Karimeen Pollichathu (Pearl Spot Fish in Banana Leaf)",
      "Appam with Vegetable / Chicken Stew",
      "Kerala Malabar Parotta & Beef/Chicken Roast",
    ],
    localTransitTips: [
      "Kochi Airport (COK) is the primary gateway, 3 hours drive to Munnar.",
      "KSRTC air-conditioned buses connect Ernakulam to Munnar daily.",
    ],
    localLanguage: "Malayalam & English",
    localPhrases: [
      { phrase: "Namaskaram", meaning: "Hello / Respectful Greeting", pronunciation: "Nuh-mus-kah-rum" },
      { phrase: "Nanni", meaning: "Thank you", pronunciation: "Nun-nee" },
      { phrase: "Sugamano?", meaning: "How are you? / Are you well?", pronunciation: "Soo-kham-ah-noh" },
    ],
    isFeatured: true,
  },
  {
    id: "dest-varanasi-up",
    name: "Varanasi (Kashi)",
    state: "Uttar Pradesh",
    region: "North India",
    tagline: "The Spiritual Capital of India & Sacred Ghats",
    description:
      "One of the oldest continuously inhabited cities on earth. Witness the mesmerizing evening Maha Aarti along the Ganga, wander ancient labyrinthine alleys, and experience profound spiritual heritage.",
    coverImage:
      "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1571536802807-30451e3955d8?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 6100,
    costIndex: "₹",
    avgDailyCostINR: 2600,
    bestTimeToVisit: "October to March (Cool river breezes)",
    idealDuration: "3 - 4 Days",
    travelStyles: ["Spiritual & Yoga", "Culture & Heritage", "Photography", "Food Walks"],
    topAttractions: [
      "Dashashwamedh Ghat Grand Evening Ganga Aarti",
      "Sunrise Boat Ride across Assi to Manikarnika Ghat",
      "Kashi Vishwanath Temple Corridor",
      "Sarnath (Where Buddha gave his first sermon)",
      "Banaras Silk Weavers Colony",
    ],
    signatureCuisine: [
      "Banarasi Tamatar Chaat & Palak Chaat",
      "Kachori Sabzi with Jalebi for breakfast",
      "Malaiyo (Winter saffron milk foam dessert)",
      "Authentic Banarasi Meetha Paan",
    ],
    localTransitTips: [
      "Old Kashi alleys are pedestrian only; walk or use cycle rickshaws.",
      "Private and shared hand-rowed boats can be negotiated at Assi Ghat.",
      "Vande Bharat trains run directly from New Delhi to Varanasi Junction.",
    ],
    localLanguage: "Bhojpuri & Hindi",
    localPhrases: [
      { phrase: "Har Har Mahadev", meaning: "Sacred City Greeting", pronunciation: "Hur Hur Muh-hah-dayv" },
      { phrase: "Ka ho bhaiya, ka haal ba?", meaning: "Hey brother, how are things?", pronunciation: "Kaa ho bhye-ya, kaa haal baa" },
      { phrase: "Dhanyawad", meaning: "Thank you", pronunciation: "Dhun-yuh-waad" },
    ],
    isFeatured: true,
  },
  {
    id: "dest-goa",
    name: "Goa (North & South)",
    state: "Goa",
    region: "West India",
    tagline: "Sun-Kissed Beaches, Portuguese Quarters & Seafood",
    description:
      "A coastal sanctuary blending relaxed beach shacks, Portuguese heritage villas in Fontainhas, spice farms, ocean water sports, and tranquil South Goa coves.",
    coverImage:
      "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1587922546307-776227941871?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 7800,
    costIndex: "₹₹",
    avgDailyCostINR: 4500,
    bestTimeToVisit: "November to February (Beach season) | July to September (Lush green monsoon)",
    idealDuration: "4 - 7 Days",
    travelStyles: ["Beaches & Coastal", "Nightlife & Cafes", "Heritage", "Water Sports"],
    topAttractions: [
      "Palolem & Agonda Beach (Tranquil South Goa)",
      "Fontainhas Latin Quarter (Panaji)",
      "Dudhsagar Waterfalls Trek & Jeep Safari",
      "Basilica of Bom Jesus & Se Cathedral (Old Goa)",
      "Aguada & Chapora Forts",
    ],
    signatureCuisine: [
      "Goan Fish Curry with Rice",
      "Prawn Balchão & Crab Xec Xec",
      "Goan Poi Bread with Chourico / Mushroom",
      "Bebinca & Feni",
    ],
    localTransitTips: [
      "Renting a scooter (₹350-500/day) or self-drive car is the most convenient way to explore.",
      "Goa App & GoaMiles cab booking are available across North & South Goa.",
    ],
    localLanguage: "Konkani, Marathi & English",
    localPhrases: [
      { phrase: "Deu borem korum", meaning: "May God do good to you (Thank you)", pronunciation: "Day-oo boh-rem koh-room" },
      { phrase: "Kitem chol'lam?", meaning: "What's up?", pronunciation: "Kee-tem chol-lahm" },
      { phrase: "Sussegado", meaning: "Relaxed state of contentment", pronunciation: "Soo-seh-gah-doh" },
    ],
    isFeatured: true,
  },
  {
    id: "dest-ladakh",
    name: "Leh Ladakh",
    state: "Ladakh",
    region: "North India",
    tagline: "High-Altitude Desert, Monasteries & Azure Lakes",
    description:
      "A dramatic moonscape nestled in the Himalayas. Cross the highest motorable passes, marvel at Pangong Tso's changing hues, and discover ancient Buddhist gompas.",
    coverImage:
      "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1598091383021-15ddea10925d?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 4120,
    costIndex: "₹₹₹",
    avgDailyCostINR: 6000,
    bestTimeToVisit: "May to September (All passes open, pleasant weather)",
    idealDuration: "6 - 8 Days",
    travelStyles: ["Adventure & Treks", "Biking & Road Trips", "Stargazing", "Culture"],
    topAttractions: [
      "Pangong Tso Lake (14,270 ft)",
      "Nubra Valley & Hunder Sand Dunes (Double-humped camels)",
      "Khardung La Pass (World's iconic high pass)",
      "Thiksey & Diskit Monasteries",
      "Magnetic Hill & Sangam (Indus-Zanskar confluence)",
    ],
    signatureCuisine: ["Ladakhi Thukpa", "Skyu (Traditional Ladakhi Stew)", "Butter Tea (Gur Gur Chai)", "Steamed Tingmo & Momos"],
    localTransitTips: [
      "Essential: Spend the first 24-48 hours in Leh for altitude acclimatization.",
      "Inner Line Permit (ILP) required for Pangong, Nubra & Tso Moriri (easily applied online).",
    ],
    localLanguage: "Ladakhi, Tibetan & Hindi",
    localPhrases: [
      { phrase: "Julley!", meaning: "Hello / Goodbye / Thank you", pronunciation: "Joo-lay" },
      { phrase: "Khamzang?", meaning: "How are you?", pronunciation: "Khum-zung" },
    ],
    isFeatured: true,
  },
  {
    id: "dest-hampi-karnataka",
    name: "Hampi (Vijayanagara Ruins)",
    state: "Karnataka",
    region: "South India",
    tagline: "UNESCO Boulder-Strewn Ancient Empire",
    description:
      "A surreal open-air museum where boulder-strewn hills frame monumental granite temples, royal baths, and the legendary Stone Chariot along the Tungabhadra River.",
    coverImage:
      "https://images.unsplash.com/photo-1600100397608-f010f4439c36?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1600100397608-f010f4439c36?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 3100,
    costIndex: "₹",
    avgDailyCostINR: 2800,
    bestTimeToVisit: "October to February (Pleasant weather for cycling & walking)",
    idealDuration: "3 - 4 Days",
    travelStyles: ["Heritage & Architecture", "Bouldering & Treks", "Photography", "Cafes"],
    topAttractions: [
      "Virupaksha Temple & Hampi Bazaar",
      "Vittala Temple & Musical Pillars (Stone Chariot)",
      "Coracle Boat Ride on Tungabhadra River",
      "Sunset from Matanga Hill / Anjaneya Hill",
      "Lotus Mahal & Elephant Stables",
    ],
    signatureCuisine: ["South Indian Banana Leaf Thali", "Bisi Bele Bath", "Mangalore Buns", "Fresh Coconut Water & Filter Coffee"],
    localTransitTips: [
      "Rent a bicycle (₹150/day) or moped (₹400/day) to traverse the ruins comfortably.",
      "Nearest railway station is Hosapete Junction (HPT), 13 km away.",
    ],
    localLanguage: "Kannada & English",
    localPhrases: [
      { phrase: "Namaskara", meaning: "Hello / Greetings", pronunciation: "Nuh-mus-kah-ruh" },
      { phrase: "Dhanyavada", meaning: "Thank you", pronunciation: "Dhun-yuh-vah-duh" },
      { phrase: "Hegiddira?", meaning: "How are you?", pronunciation: "Hay-gid-dee-rah" },
    ],
  },
  {
    id: "dest-meghalaya",
    name: "Meghalaya (Cherrapunji & Mawlynnong)",
    state: "Meghalaya",
    region: "East & North East",
    tagline: "Abode of the Clouds & Living Root Bridges",
    description:
      "Walk among cascading jungle waterfalls, cross bio-engineered double-decker living root bridges grown by the Khasi tribe, and boat on crystal transparent rivers in Dawki.",
    coverImage:
      "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 2950,
    costIndex: "₹₹",
    avgDailyCostINR: 3900,
    bestTimeToVisit: "October to April (Crystal clear Dawki river) | May to September (Roaring waterfalls)",
    idealDuration: "5 - 6 Days",
    travelStyles: ["Nature & Treks", "Eco-Tourism", "Indigenous Culture", "Adventure"],
    topAttractions: [
      "Nongriat Double Decker Living Root Bridge Trek",
      "Umngot River Boating at Dawki (Crystal Clear Glass Water)",
      "Nohkalikai Falls (India's tallest plunge waterfall)",
      "Mawlynnong (Asia's Cleanest Village)",
      "Mawsmai Limestone Caves",
    ],
    signatureCuisine: ["Jadoh (Khasi rice cooked with herbs)", "Dohneiiong (Pork with black sesame)", "Tungrymbai", "Fresh Pineapple & Bamboo Shoot Salad"],
    localTransitTips: [
      "Fly to Guwahati Airport (GAU) and hire a dedicated tourist taxi for Meghalaya.",
      "Carry sturdy waterproof trekking shoes for the 3,000 steps Nongriat trek.",
    ],
    localLanguage: "Khasi, Garo & English",
    localPhrases: [
      { phrase: "Khublei", meaning: "Thank you / Greetings", pronunciation: "Khoo-blay" },
      { phrase: "Kumno?", meaning: "How are you?", pronunciation: "Koom-noh" },
    ],
  },
  {
    id: "dest-andaman",
    name: "Andaman & Nicobar Islands (Havelock)",
    state: "Andaman and Nicobar Islands",
    region: "Islands",
    tagline: "Turquoise Coral Reefs & Pristine White Sands",
    description:
      "A tropical island paradise in the Bay of Bengal with Asia's best beach (Radhanagar), vibrant coral reefs for scuba diving, night bioluminescence kayaking, and cellular jail history in Port Blair.",
    coverImage:
      "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 3800,
    costIndex: "₹₹₹",
    avgDailyCostINR: 5800,
    bestTimeToVisit: "October to May (Calm seas & optimal water clarity)",
    idealDuration: "5 - 7 Days",
    travelStyles: ["Beaches & Islands", "Scuba & Snorkeling", "Romantic", "Wildlife & Marine"],
    topAttractions: [
      "Radhanagar Beach (Beach No. 7 - Havelock)",
      "Elephant Beach Coral Reef Snorkeling & Sea Walk",
      "Night Bioluminescence Kayaking at Havelock Mangroves",
      "Cellular Jail Light & Sound Show (Port Blair)",
      "Neil Island Natural Rock Formation (Howrah Bridge)",
    ],
    signatureCuisine: ["Fresh Catch Grilled Lobster & King Prawns", "Coconut Prawn Curry", "Tandoori Fish", "Tropical Mango & Coconut Smoothies"],
    localTransitTips: [
      "Private Catamarans (Makruzz, Nautika, Green Ocean) run between Port Blair, Havelock & Neil.",
      "Pre-book ferry tickets well in advance during peak winter season.",
    ],
    localLanguage: "Hindi, Bengali, Tamil & English",
    localPhrases: [
      { phrase: "Namaste", meaning: "Hello / Greetings", pronunciation: "Nuh-mus-tay" },
      { phrase: "Dhanyawad / Shukriya", meaning: "Thank you", pronunciation: "Dhun-yuh-waad" },
    ],
  },
  {
    id: "dest-rishikesh",
    name: "Rishikesh & Haridwar",
    state: "Uttarakhand",
    region: "North India",
    tagline: "Yoga Capital of the World & Himalayan Foothills",
    description:
      "Where the emerald Ganga descends into the plains. Famed for yoga ashrams, the Beatles Ashram, thrilling river rafting, cliff jumping, and Har Ki Pauri Ganga Aarti.",
    coverImage:
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 4500,
    costIndex: "₹",
    avgDailyCostINR: 2400,
    bestTimeToVisit: "September to June (Rafting open from late September to June)",
    idealDuration: "3 - 5 Days",
    travelStyles: ["Spiritual & Yoga", "Adventure Sports", "Riverfront Camping", "Cafes"],
    topAttractions: [
      "Ganga River White Water Rafting (Shivpuri to Rishikesh)",
      "Triveni Ghat & Parmarth Niketan Evening Ganga Aarti",
      "Beatles Ashram (Chaurasi Kutia)",
      "Har Ki Pauri Evening Aarti in Haridwar",
      "Neer Garh Waterfall Trek",
    ],
    signatureCuisine: ["Satvik Ayurvedic Thali", "Aloo Poori at Mohanji Puri Wale", "Ginger Lemon Honey Tea", "Kullad Rabri & Lassi"],
    localTransitTips: [
      "Direct Vande Bharat trains connect Delhi to Haridwar / Dehradun.",
      "Walk across Ram Jhula and Lakshman Jhula area or hire scooters.",
    ],
    localLanguage: "Garhwali & Hindi",
    localPhrases: [
      { phrase: "Jai Gange!", meaning: "Hail the Holy Ganga (Local Greeting)", pronunciation: "Jye Gun-gay" },
      { phrase: "Dhanyawad", meaning: "Thank you", pronunciation: "Dhun-yuh-waad" },
    ],
  },
];
