import { Experience } from "../types";

export const INDIAN_EXPERIENCES: Experience[] = [
  {
    id: "exp-dal-lake-shikara",
    title: "Sunrise Shikara Ride & Floating Flower Market",
    destination: "Srinagar & Gulmarg",
    state: "Jammu & Kashmir",
    region: "North India",
    category: "Culture & History",
    coverImage: "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=800&q=80",
    priceINR: 1200,
    duration: "2.5 Hours",
    rating: 4.9,
    reviews: 1420,
    description: "Glide silently across the mirrored waters of Dal Lake at dawn. Witness the world's only floating vegetable & saffron flower market while sipping hot Kehwa with Kashmiri almonds.",
    includes: ["Private traditional carved Shikara boat", "Kashmiri Kehwa tea with dry fruits", "Local boatman storytelling", "Floating market stops"],
    bestTime: "05:30 AM - 08:00 AM",
  },
  {
    id: "exp-varanasi-ganga-aarti",
    title: "Vip Evening Ganga Aarti Boat & Floating Lamps",
    destination: "Varanasi (Kashi)",
    state: "Uttar Pradesh",
    region: "North India",
    category: "Spiritual & Wellness",
    coverImage: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80",
    priceINR: 850,
    duration: "2 Hours",
    rating: 5.0,
    reviews: 2890,
    description: "Front-row boat seating facing Dashashwamedh Ghat during the legendary Vedic fire ceremony. Release glowing oil diyas into the sacred river as chanting and bells echo across the night.",
    includes: ["Boat vantage point right in front of the priests", "Floral oil diyas for release", "Local Vedic priest historical commentary", "Banarasi sweet box"],
    bestTime: "06:00 PM - 08:00 PM",
  },
  {
    id: "exp-jaipur-hot-air-balloon",
    title: "Sunrise Hot Air Balloon over Jaipur Forts & Palaces",
    destination: "Jaipur",
    state: "Rajasthan",
    region: "West India",
    category: "Adventure",
    coverImage: "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=800&q=80",
    priceINR: 11500,
    duration: "3.5 Hours (60 min flight)",
    rating: 4.9,
    reviews: 640,
    description: "Drift serenely above Amer Fort, Aravalli ridges, and remote Rajasthani heritage villages as the morning sun casts a golden glow over the Pink City.",
    includes: ["60-minute hot air balloon flight", "DGCA certified European flight captain", "Continental breakfast on landing", "First flight commemorative certificate"],
    bestTime: "05:45 AM - 09:15 AM",
  },
  {
    id: "exp-kerala-houseboat-cruise",
    title: "Luxury Houseboat Cruise with Traditional Kerala Sadhya",
    destination: "Alleppey Backwaters",
    state: "Kerala",
    region: "South India",
    category: "Nature & Wildlife",
    coverImage: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80",
    priceINR: 8500,
    duration: "Full Day / Overnight",
    rating: 4.9,
    reviews: 1980,
    description: "Sail through emerald canals, paddy fields, and village shores on a private wooden Kettuvallam with an onboard chef cooking authentic Karimeen fish and 24-dish banana leaf Sadhya.",
    includes: ["Private 1-bedroom / 2-bedroom AC houseboat", "Dedicated captain, guide, and private chef", "Welcome fresh tender coconut", "Full 4-course traditional Kerala meals"],
    bestTime: "11:30 AM Check-in",
  },
  {
    id: "exp-havelock-scuba-diving",
    title: "PADI Certified Coral Reef Scuba Dive at Havelock",
    destination: "Andaman Islands",
    state: "Andaman and Nicobar Islands",
    region: "Islands",
    category: "Adventure",
    coverImage: "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&w=800&q=80",
    priceINR: 4200,
    duration: "3 Hours (45 min underwater)",
    rating: 4.8,
    reviews: 1250,
    description: "Immerse into crystal turquoise waters at Nemo Reef. Encounter vibrant clownfish, sea turtles, manta rays, and pristine coral formations with 1-on-1 dive instructor guidance.",
    includes: ["Full Scuba gear & wetsuit", "Dedicated PADI dive instructor (1:1 ratio)", "Underwater high-res 4K photos & videos", "Pre-dive training in shallow water"],
    bestTime: "06:30 AM or 09:30 AM",
  },
  {
    id: "exp-hampi-coracle-bouldering",
    title: "Coracle Boat Ride & Matanga Hill Bouldering Sunset",
    destination: "Hampi",
    state: "Karnataka",
    region: "South India",
    category: "Culture & History",
    coverImage: "https://images.unsplash.com/photo-1600100397608-f010f4439c36?auto=format&fit=crop&w=800&q=80",
    priceINR: 950,
    duration: "4 Hours",
    rating: 4.9,
    reviews: 820,
    description: "Spin across the ancient Tungabhadra River in a woven wicker coracle boat, explore submerged temple shrines, and hike up Matanga Hill for a 360-degree sunset over the empire ruins.",
    includes: ["Traditional coracle boat ride with skilled navigator", "Guided heritage hike of boulder trails", "Safety life-jackets", "Hampi archaeological commentary"],
    bestTime: "03:30 PM - 07:00 PM",
  },
  {
    id: "exp-goa-fontainhas-walk",
    title: "Old Goa Heritage Walk & Fontainhas Latin Quarter Food Trail",
    destination: "Panaji & Old Goa",
    state: "Goa",
    region: "West India",
    category: "Food & Drink",
    coverImage: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80",
    priceINR: 1500,
    duration: "3 Hours",
    rating: 4.8,
    reviews: 940,
    description: "Wander through pastel-hued Portuguese villas, 18th-century churches, and quaint bakeries. Taste freshly baked Poi, Goan beef/mushroom croquettes, and authentic Bebinca.",
    includes: ["Historian guided walking tour", "Tastings at 4 heritage bakeries & taverns", "Bebinca dessert & Goan feni tasting (21+)", "Architectural photo booklet"],
    bestTime: "04:00 PM - 07:00 PM",
  },
  {
    id: "exp-rishikesh-river-rafting",
    title: "Shivpuri to Rishikesh 16km White Water Rafting & Cliff Jump",
    destination: "Rishikesh",
    state: "Uttarakhand",
    region: "North India",
    category: "Adventure",
    coverImage: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    priceINR: 1400,
    duration: "4 Hours",
    rating: 4.9,
    reviews: 3100,
    description: "Conquer Grade III & IV rapids including 'Roller Coaster', 'Golf Course', and 'Club House' on the pristine roaring Ganga with an exhilarating 25-foot cliff jumping session.",
    includes: ["Grade-approved raft & safety gear (helmets/lifejackets)", "Certified IRF river guide", "Cliff jump and body surfing experience", "Transit from office to Shivpuri launch pad"],
    bestTime: "09:00 AM or 01:00 PM",
  },
];
