import { Trip } from "../types";

export const SAMPLE_TRIPS: Trip[] = [
  {
    id: "trip-rajasthan-royals",
    title: "Royal Rajasthan & Golden Triangle",
    destination: "Jaipur, Udaipur & Jodhpur",
    state: "Rajasthan",
    region: "West India",
    startDate: "2026-10-12",
    endDate: "2026-10-17",
    durationDays: 6,
    budgetINR: 55000,
    spentINR: 38400,
    status: "Booked",
    coverImage:
      "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1200&q=80",
    description:
      "A royal heritage expedition through the pink palaces of Jaipur, the hilltop forts of Amer, and romantic lakeside dining in Udaipur.",
    travelersCount: 2,
    tags: ["Heritage & Palaces", "Royal Architecture", "Culinary Trail"],
    collaborators: ["alex.traveler@gmail.com", "priya.sharma@gmail.com"],
    createdAt: "2026-08-01",
    days: [
      {
        dayNumber: 1,
        dateStr: "Oct 12, 2026",
        title: "Arrival in Pink City & Old Bazaars",
        theme: "Heritage First Impressions",
        activities: [
          {
            id: "act-1-1",
            time: "10:30 AM",
            title: "Check-in at Heritage Haveli Hotel",
            location: "Civil Lines, Jaipur",
            category: "Stay",
            description: "Traditional welcome with marigold garlands and saffron sherbet.",
            estimatedCostINR: 6500,
            duration: "1 Hour",
            isCompleted: true,
          },
          {
            id: "act-1-2",
            time: "01:00 PM",
            title: "Royal Thali Lunch at LMB (Laxmi Mishtan Bhandar)",
            location: "Johari Bazaar, Jaipur",
            category: "Food",
            description: "Authentic Rajasthani thali featuring Dal Baati Churma, Gatte ki Sabzi, Ker Sangri, and Ghewar.",
            estimatedCostINR: 1600,
            duration: "1.5 Hours",
            isCompleted: true,
          },
          {
            id: "act-1-3",
            time: "03:30 PM",
            title: "City Palace & Jantar Mantar Observatory",
            location: "Old City, Jaipur",
            category: "Sightseeing",
            description: "Tour the royal courtyards, Chandra Mahal museum, and the world's largest stone sundial.",
            estimatedCostINR: 1200,
            duration: "2.5 Hours",
            isCompleted: true,
          },
          {
            id: "act-1-4",
            time: "06:30 PM",
            title: "Sunset over Hawa Mahal & Rooftop Tea",
            location: "Tattoo Cafe / Wind View Cafe",
            category: "Culture",
            description: "Spectacular vantage point overlooking the 953 honeycomb windows of the Palace of Winds.",
            estimatedCostINR: 700,
            duration: "1.5 Hours",
            isCompleted: true,
          },
        ],
      },
      {
        dayNumber: 2,
        dateStr: "Oct 13, 2026",
        title: "Amer Fort Bastions & Nahargarh Sunset",
        theme: "Fortresses & Panoramic Vistas",
        activities: [
          {
            id: "act-2-1",
            time: "08:30 AM",
            title: "Amer Fort & Sheesh Mahal Exploration",
            location: "Amer, Jaipur",
            category: "Sightseeing",
            description: "Explore the mirrored hall of Sheesh Mahal, Diwan-e-Khas, and Maota Lake reflections.",
            estimatedCostINR: 1000,
            duration: "3 Hours",
            isCompleted: true,
          },
          {
            id: "act-2-2",
            time: "01:30 PM",
            title: "Panna Meena Ka Kund Stepwell & Sanganer Pottery",
            location: "Amer Village",
            category: "Culture",
            description: "Visit the geometric 16th-century stepwell and artisan blue pottery workshops.",
            estimatedCostINR: 500,
            duration: "2 Hours",
            isCompleted: false,
          },
          {
            id: "act-2-3",
            time: "05:00 PM",
            title: "Nahargarh Fort Sunset Point & Padao Lounge",
            location: "Aravalli Hills",
            category: "Adventure",
            description: "Sunset drinks overlooking the entire lit-up cityscape of Jaipur.",
            estimatedCostINR: 1500,
            duration: "2.5 Hours",
            isCompleted: false,
          },
        ],
      },
      {
        dayNumber: 3,
        dateStr: "Oct 14, 2026",
        title: "Vande Bharat Express to Udaipur & Lake Pichola",
        theme: "City of Lakes & Serenade",
        activities: [
          {
            id: "act-3-1",
            time: "06:15 AM",
            title: "Vande Bharat Express Train (Jaipur to Udaipur)",
            location: "Jaipur Junction Railway Station",
            category: "Transit",
            description: "Smooth 6-hour high-speed train ride through the Aravalli valleys with onboard breakfast.",
            estimatedCostINR: 2800,
            duration: "6 Hours",
            isCompleted: false,
          },
          {
            id: "act-3-2",
            time: "04:30 PM",
            title: "Lake Pichola Sunset Boat Cruise & Jag Mandir",
            location: "Rameshwar Ghat, Udaipur",
            category: "Sightseeing",
            description: "Cruise around the floating Taj Lake Palace and step ashore at the historic island palace of Jag Mandir.",
            estimatedCostINR: 1800,
            duration: "2 Hours",
            isCompleted: false,
          },
          {
            id: "act-3-3",
            time: "07:30 PM",
            title: "Dharohar Folk Dance Show at Bagore Ki Haveli",
            location: "Gangaur Ghat, Udaipur",
            category: "Culture",
            description: "Live Rajasthani music, Chari fire dance, and the famous 10-pot head balance dance.",
            estimatedCostINR: 800,
            duration: "1.5 Hours",
            isCompleted: false,
          },
        ],
      },
    ],
    expenses: [
      {
        id: "exp-1",
        date: "2026-10-12",
        title: "Heritage Haveli Stay (3 Nights)",
        category: "Accommodation",
        amountINR: 19500,
        paymentMethod: "Credit Card",
        paidBy: "Alex",
        receiptNote: "Booking ID: RJ-HAV-9821",
      },
      {
        id: "exp-2",
        date: "2026-10-12",
        title: "LMB Royal Thali & Sweets",
        category: "Meals & Dining",
        amountINR: 1600,
        paymentMethod: "UPI",
        paidBy: "Alex",
      },
      {
        id: "exp-3",
        date: "2026-10-12",
        title: "City Palace Composite Tickets & Guide",
        category: "Activities",
        amountINR: 1700,
        paymentMethod: "UPI",
        paidBy: "Priya",
      },
      {
        id: "exp-4",
        date: "2026-10-13",
        title: "AC Tourist Cab for Amer & Nahargarh",
        category: "Transport",
        amountINR: 2200,
        paymentMethod: "Cash",
        paidBy: "Alex",
      },
      {
        id: "exp-5",
        date: "2026-10-13",
        title: "Block Print Dupattas at Johari Bazaar",
        category: "Shopping",
        amountINR: 4800,
        paymentMethod: "UPI",
        paidBy: "Priya",
      },
      {
        id: "exp-6",
        date: "2026-10-14",
        title: "IRCTC Vande Bharat Executive Chair Car Tickets",
        category: "Transport",
        amountINR: 5600,
        paymentMethod: "Net Banking",
        paidBy: "Alex",
        receiptNote: "PNR: 2849104822",
      },
      {
        id: "exp-7",
        date: "2026-10-14",
        title: "Lake Pichola Sunset Boat Tickets",
        category: "Activities",
        amountINR: 3000,
        paymentMethod: "UPI",
        paidBy: "Alex",
      },
    ],
  },
  {
    id: "trip-kashmir-wonderland",
    title: "Kashmir Gulmarg Snow & Shikara Retreat",
    destination: "Gulmarg, Srinagar & Pahalgam",
    state: "Jammu & Kashmir",
    region: "North India",
    startDate: "2026-12-20",
    endDate: "2026-12-25",
    durationDays: 5,
    budgetINR: 60000,
    spentINR: 24500,
    status: "Planning",
    coverImage:
      "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=1200&q=80",
    description:
      "Winter snow holiday in Gulmarg with Phase 2 Gondola skiing, cedarwood houseboats in Dal Lake, and saffron farms in Pampore.",
    travelersCount: 2,
    tags: ["Snow & Mountains", "Shikara Cruises", "Winter Wonderland"],
    collaborators: ["alex.traveler@gmail.com"],
    createdAt: "2026-08-10",
    days: [
      {
        dayNumber: 1,
        dateStr: "Dec 20, 2026",
        title: "Arrival in Srinagar & Dal Lake Houseboat",
        theme: "Valley of Tranquility",
        activities: [
          {
            id: "kash-1-1",
            time: "11:00 AM",
            title: "Check-in at Luxury Heritage Houseboat",
            location: "Nigeen Lake / Dal Lake, Srinagar",
            category: "Stay",
            description: "Wood-carved Kashmiri houseboat overlooking floating water lilies and misty mountain reflections.",
            estimatedCostINR: 7500,
            duration: "2 Hours",
            isCompleted: false,
          },
          {
            id: "kash-1-2",
            time: "03:30 PM",
            title: "Sunset Shikara Ride & Floating Market",
            location: "Dal Lake, Srinagar",
            category: "Sightseeing",
            description: "Serene ride to Char Chinar with Kashmiri Kahwa tea served on board.",
            estimatedCostINR: 1200,
            duration: "2.5 Hours",
            isCompleted: false,
          },
          {
            id: "kash-1-3",
            time: "07:30 PM",
            title: "Traditional Kashmiri Wazwan Feast",
            location: "Ahdoos / Mughal Darbar, Srinagar",
            category: "Food",
            description: "Rogan Josh, Gustaba, Rista, Tabak Maaz, and Kashmiri Saffron Rice.",
            estimatedCostINR: 2200,
            duration: "2 Hours",
            isCompleted: false,
          },
        ],
      },
      {
        dayNumber: 2,
        dateStr: "Dec 21, 2026",
        title: "Gulmarg Gondola & Snow Slopes",
        theme: "Alpine Adventure",
        activities: [
          {
            id: "kash-2-1",
            time: "08:00 AM",
            title: "Scenic Snow Drive to Gulmarg",
            location: "Tangmarg to Gulmarg",
            category: "Transit",
            description: "Chain-wheel drive through snow-laden pine forests.",
            estimatedCostINR: 2500,
            duration: "2 Hours",
            isCompleted: false,
          },
          {
            id: "kash-2-2",
            time: "10:30 AM",
            title: "Gulmarg Gondola (Phase 1 to Kongdoori & Phase 2 to Apharwat)",
            location: "Gulmarg Cable Car Station",
            category: "Adventure",
            description: "Ride to 13,780 ft on the world's second highest operating cable car with breathtaking snow panoramas.",
            estimatedCostINR: 4000,
            duration: "4 Hours",
            isCompleted: false,
          },
        ],
      },
    ],
    expenses: [
      {
        id: "k-exp-1",
        date: "2026-08-12",
        title: "Houseboat & Hotel Advance Deposit",
        category: "Accommodation",
        amountINR: 15000,
        paymentMethod: "Credit Card",
        paidBy: "Alex",
      },
      {
        id: "k-exp-2",
        date: "2026-08-14",
        title: "JK Cable Car Phase 1 & 2 Tickets",
        category: "Activities",
        amountINR: 4000,
        paymentMethod: "UPI",
        paidBy: "Alex",
      },
      {
        id: "k-exp-3",
        date: "2026-08-15",
        title: "Pre-booked Srinagar Airport Cabs",
        category: "Transport",
        amountINR: 5500,
        paymentMethod: "UPI",
        paidBy: "Alex",
      },
    ],
  },
  {
    id: "trip-kerala-backwaters",
    title: "Kerala Backwaters & Munnar Tea Odyssey",
    destination: "Munnar, Thekkady & Alleppey",
    state: "Kerala",
    region: "South India",
    startDate: "2026-09-05",
    endDate: "2026-09-10",
    durationDays: 5,
    budgetINR: 45000,
    spentINR: 44200,
    status: "Completed",
    coverImage:
      "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80",
    description:
      "Misty tea hill hikes in Munnar, spice garden walks in Thekkady, and a private overnight houseboat cruise in Alleppey.",
    travelersCount: 2,
    tags: ["Nature & Greenery", "Houseboat Cruise", "Ayurveda & Tea"],
    collaborators: ["alex.traveler@gmail.com"],
    createdAt: "2026-07-15",
    days: [],
    expenses: [
      {
        id: "ker-exp-1",
        date: "2026-09-05",
        title: "Munnar Tea Resort Stay (2 Nights)",
        category: "Accommodation",
        amountINR: 14000,
        paymentMethod: "Credit Card",
        paidBy: "Alex",
      },
      {
        id: "ker-exp-2",
        date: "2026-09-07",
        title: "Alleppey AC Houseboat Overnight Cruise",
        category: "Accommodation",
        amountINR: 11000,
        paymentMethod: "UPI",
        paidBy: "Alex",
      },
      {
        id: "ker-exp-3",
        date: "2026-09-08",
        title: "Private Sedan Chauffeur (Kochi-Munnar-Alleppey)",
        category: "Transport",
        amountINR: 12500,
        paymentMethod: "UPI",
        paidBy: "Alex",
      },
      {
        id: "ker-exp-4",
        date: "2026-09-09",
        title: "Authentic Spices, Tea & Banana Chips",
        category: "Shopping",
        amountINR: 6700,
        paymentMethod: "Cash",
        paidBy: "Alex",
      },
    ],
  },
];
